//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DataPatterns.EntityFramework.Foo
{
    public partial class FOOEntities : DbContext
    {
        public FOOEntities()
            : base("name=FOOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Documents> Documents { get; set; }
        public DbSet<Ressource> Ressource { get; set; }
        public DbSet<RefPlanNumerotation> RefPlanNumerotation { get; set; }
        public DbSet<RefEtatRessource> RefEtatRessource { get; set; }
        public DbSet<DemandeImplementation> DemandeImplementation { get; set; }
        public DbSet<Destination> Destination { get; set; }
        public DbSet<RefCategorieDestination> RefCategorieDestination { get; set; }
        public DbSet<RefPays> RefPays { get; set; }
    }
}
