//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DataPatterns.EntityFramework.Foo
{
    public partial class Destination
    {
        public Destination()
        {
            this.RessourceInt = new HashSet<RessourceInt>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Libelle { get; set; }
        public int RefPaysId { get; set; }
        public int RefCategorieDestinationId { get; set; }
        public int RefStatutId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateOuverture { get; set; }
        public Nullable<System.DateTime> DateFermeture { get; set; }
    
        public virtual ICollection<RessourceInt> RessourceInt { get; set; }
        public virtual RefCategorieDestination RefCategorieDestination { get; set; }
        public virtual RefPays RefPays { get; set; }
    }
    
}
