//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DataPatterns.EntityFramework.Foo
{
    public partial class RessourceNatDom : Ressource
    {
        public Nullable<int> RefZneId { get; set; }
        public Nullable<int> RoutageId { get; set; }
        public Nullable<int> ClasseId { get; set; }
        public Nullable<int> RefAllocationSpecId { get; set; }
        public int TypeRessourceId { get; set; }
        public Nullable<int> RefSgtqsId { get; set; }
        public string DecisionArcep { get; set; }
        public Nullable<System.DateTime> DateAttribution { get; set; }
        public int AttributaireId { get; set; }
        public Nullable<int> MandataireId { get; set; }
    }
    
}
