//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DataPatterns.EntityFramework
{
    public partial class AdventureWorks2008R2Entities : DbContext
    {
        public AdventureWorks2008R2Entities()
            : base("name=AdventureWorks2008R2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BusinessEntity> BusinessEntity { get; set; }
        public DbSet<Person> Person { get; set; }
    }
}
